FROM nginx:latest

RUN apt-get update && apt-get install -y gettext-base

COPY ../frontend /usr/share/nginx/html

COPY ../config.template.js /usr/share/nginx/html/config.template.js

COPY ../nginx.conf /etc/nginx/conf.d/default.conf

COPY ../010-populate_config_template.sh /docker-entrypoint.d/010-populate_config_template.sh