FROM python:3.10.13

RUN apt-get update && apt-get install -y parallel findutils

WORKDIR /app

COPY ../fetcher /app

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /app/get_items_test.sh
RUN /app/get_items_test.sh

RUN find data -type f -name "*.txt" | parallel -j 4 -N 64 --bar python gather.py > all.jsonl

CMD ["sh", "-c", "python insert.py all.jsonl --batch-size 8"]

